Handle text error responses
odannyc/go-openai pull request #1
Opened 2024-02-21 20:14 UTC by prashkan

A similar PR may already be submitted!
Please search among the [Pull request](https://github.com/sashabaranov/go-openai/pulls) before creating one.

If your changes introduce breaking changes, please prefix the title of your pull request with "[BREAKING_CHANGES]". This allows for clear identification of such changes in the 'What's Changed' section on the release page, making it developer-friendly.

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request.

**Describe the change**
Please provide a clear and concise description of the changes you're proposing. Explain what problem it solves or what feature it adds.

**Provide OpenAI documentation link**
Provide a relevant API doc from https://platform.openai.com/docs/api-reference

**Describe your solution**
Describe how your changes address the problem or how they add the feature. This should include a brief description of your approach and any new libraries or dependencies you're using.

**Tests**
Briefly describe how you have tested these changes. If possible — please add integration tests.

**Additional context**
Add any other context or screenshots or logs about your pull request here. If the pull request relates to an open issue, please link to it.

Issue: #XXXX

2024-02-21 22:00 UTC, Aerendel approved these changes

2024-02-21 22:00 UTC, odannyc requested changes

2024-02-21 22:00 UTC, odannyc commented on client.go
> +	mainContentType := strings.Split(contentType, ";")[0]
Should we verify here that splitting the contentType header does infact return results - otherwise we could gracefully handle that. I don't think it's safe to assume the response will contain the header. With that in mind, I also don't think we should return an error if the header doesn't exist - we should probably continue assuming that the response is infact json which is what we are doing now.

2024-02-21 22:00 UTC, odannyc commented on client.go
> +		defer resp.Body.Close()
This is already handled here: https://github.com/odannyc/go-openai/blob/master/client.go#L124

2024-02-22 15:23 UTC, prashkan commented on client.go
> +	mainContentType := strings.Split(contentType, ";")[0]
Yeah looks like the content type is an optional header, so I've reworked this to check for a content type, and if so, check if it's `text/plain` - if not, we will go the JSON route.

2024-02-22 17:12 UTC, odannyc approved these changes

2024-02-22 18:24 UTC, merged